<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="43753" started-at="2016-02-20T03:54:06Z" finished-at="2016-02-20T03:54:50Z">
    <groups>
      <group name="P1">
        <method signature="TC_001.testUntitled1()[pri:0, instance:testcases.TC_001@2a7704dd]" name="testUntitled1" class="testcases.TC_001"/>
      </group> <!-- P1 -->
    </groups>
    <test name="Test" duration-ms="43753" started-at="2016-02-20T03:54:06Z" finished-at="2016-02-20T03:54:50Z">
      <class name="testcases.TC_001">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.TC_001@2a7704dd]" name="setUp" is-config="true" duration-ms="11062" started-at="2016-02-20T09:24:07Z" finished-at="2016-02-20T09:24:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="testUntitled1()[pri:0, instance:testcases.TC_001@2a7704dd]" name="testUntitled1" duration-ms="32057" started-at="2016-02-20T09:24:18Z" finished-at="2016-02-20T09:24:50Z">
          <exception class="com.thoughtworks.selenium.SeleniumException">
            <message>
              <![CDATA[Timed out after 30000ms]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.thoughtworks.selenium.SeleniumException: Timed out after 30000ms
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:111)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:105)
	at com.thoughtworks.selenium.DefaultSelenium.open(DefaultSelenium.java:372)
	at testcases.TC_001.testUntitled1(TC_001.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- com.thoughtworks.selenium.SeleniumException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUntitled1 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.TC_001@2a7704dd]" name="tearDown" is-config="true" duration-ms="615" started-at="2016-02-20T09:24:50Z" finished-at="2016-02-20T09:24:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.TC_001 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
